name: "Documentation"

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      deploy:
        description: "Whether to deploy the generated documentation to the docs repository"
        default: false
        required: false
        type: "boolean"
      component:
        description: "The component to deploy the documentation for"
        required: true
        type: "string"

jobs:
  documentation:
    name: "Documentation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Build"
        uses: "phpDocumentor/phpDocumentor@master"

      - name: "Deploy"
        if: "${{ inputs.deploy }}"
        uses: "actions/upload-artifact@v6"
        with:
          name: "documentation"
          path: "build/docs"
          retention-days: 1

  deploy:
    name: "Deploy"
    if: "${{ inputs.deploy }}"
    runs-on: "ubuntu-latest"
    needs: "documentation"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          repository: "phpDocumentor/docs"
          token: "${{ secrets.BOT_TOKEN }}"
          path: "docs"

      - name: "Download"
        uses: "actions/download-artifact@v7"
        with:
          name: "documentation"
          path: "build/docs"

      - name: "Copy files"
        run: "rsync -r --delete build/docs/* docs/docs/components/${{ inputs.component }}"

      - name: "Commit"
        uses: "stefanzweifel/git-auto-commit-action@v7"
        with:
          repository: "docs"
          commit_message: "Update ${{ inputs.component }} documentation"

      - name: "Push"
        uses: "ad-m/github-push-action@master"
        with:
          directory: "docs"
          github_token: "${{ secrets.BOT_TOKEN }}"
          repository: "phpDocumentor/docs"
